name: Convert and Deploy Jupyter Notebook to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install Jupyter
        run: |
          pip install jupyter nbconvert

      - name: Convert Notebook to HTML
        run: |
          jupyter nbconvert --to html notebooks/sales_analysis.ipynb --output sales_analysis.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./notebooks
          publish_branch: gh-pages
